[build]
  base = "frontend"
  command = "yarn install && yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Dev server configuration
[dev]
  command = "yarn start"
  port = 3000
  publish = "frontend/build"

[dev.environment]
  NODE_ENV = "development"